import 'dart:async';

import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:riverpod_project/data_source/products_data_source.dart';
import 'package:riverpod_project/providers/api_service_provider.dart';

part 'product_provider.g.dart';

// This is a provider is not auto generated
final allProductsProvider = Provider((ref) {
  return ProductsDataSource.fetchAllProducts();
});

// Provider shall be auto generated by Riverpod
@riverpod
Future<List> products(ref) {
  return ref.read(apiServiceProvider).fetchProducts();
}

@riverpod
Future<List> currentUsers(ref) {
  return ref.read(apiServiceProvider).returnUsers();
}
